language: csharp
mono: none
dotnet: 5.0

addons:
  sonarcloud:
    organization: "gmike"

before_install:
- bash ./tools/travis-ci-install-sonar.sh

install:
- dotnet restore src

script:
 - bash ./tools/travis-ci-build.sh
