language: csharp
os: linux
dist: bionic
env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: none
dotnet: 5.0

addons:
  sonarcloud:
    organization: "gmike"
    token: $SONAR_TOKEN

before_install:
  - bash ./tools/travis-ci-install-sonar.sh

install:
  - sudo apt-get install -qq dotnet-sdk-5.0
  - dotnet restore

script:
    - dotnet build    
    - bash ./tools/travis-ci-build.sh
    
