sudo: required
solution: WordsToNumber.sln
language: csharp
mono: none
dotnet: 5.0.202
git:
  depth: false
  
addons:
  sonarcloud:
    organization: "gmike"
    token: $SONAR_TOKEN

before_install:
  - bash ./tools/travis-ci-install-sonar.sh

install:
  - sudo apt-get install -qq dotnet-sdk-5.0

script:
    - dotnet build    
    - bash ./tools/travis-ci-build.sh
    
