language: csharp
os: linux
dist: bionic
env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: none
dotnet: 5.0

addons:
  sonarcloud:
    organization: "gmike"
    token:
      secure: "O8GlY84yPXb9QYuXcSHkuITfy5fRpt4y31SZrBgJGVxJG3HnCNhWuzKBFsmhUGZC7odKNuQKFPHQPEzRAfxIWQVN26lxQ3vzPgb8aKVkyIfeopJTRAUD2k/Kx4H4OLgD0mVrgG4KEQHbuQZNdrccMtS6MDOtl9OraFS/SSrfQu9oYwCz5CD+YwbgoG17f7lYOa/vqjvLg3lXyAr+aycPEvG7x+J588KvQGMxIRxQRKiPEDjljnixzV+coPzykws/bBXNOyYKsJogbW0zZAFJXOuGUjx0qe6+oTYvqWI8KP5wutO0SwN9hRPnwz+Md0Y7jVtCln45UNox55Wu8X7SV5iMTiDQtmhMRY+aakJJPGCG9PNqFkUfn8X6ZcISrCzrh6mfk41rUl29V2kVfCQ1FCk2pe6XJ+ZxgJytaJaiahLSEb/9/wQrcebofXtv6WFsh9AYnXw8mYzg/kzk8DNOCdrFUWImGwS2AOO5Xtpyrw9HSzr6Y0qzOCxGS6mfJqeGzKhSwhERnJDIaTKnOGjNNg8bErTYwgk6+uaykiliaXMCKfc+oyNSDApOuTjmGRxX2jIUERdRuvZDEb/eI/vAUbsLtbKqcp7wwc3yePTj/1HbB+K7KZzlcNmGVRUDx5AOanWPJeykifFbNXbo+bnBt33Qmw9MiniXdo3tbMNLOyM="

script:
    - dotnet build
    - sonar-scanner

